version: '3.8'

services:
  fixitfred:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fixitfred-platform
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./deployments:/app/deployments
      - ./storage:/app/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fixitfred-network

networks:
  fixitfred-network:
    driver: bridge

volumes:
  data:
  logs:
  deployments:
  storage:
